import React from "react";
import { SunIcon, MoonIcon, GearIcon, PersonIcon, QuestionMarkCircledIcon, 
    QuestionMarkIcon, CheckCircledIcon, CheckIcon, ExitIcon, CalendarIcon, 
    StarIcon, CameraIcon, CodeIcon, CodeSandboxLogoIcon, LayersIcon, InputIcon, 
    MagnifyingGlassIcon, Cross1Icon, Cross2Icon, Crosshair2Icon, GitHubLogoIcon, 
    InstagramLogoIcon, LinkedInLogoIcon, StackIcon, FileIcon, SwitchIcon, HomeIcon, 
    BellIcon, CaretUpIcon, CardStackIcon, CardStackMinusIcon, CardStackPlusIcon, PlusIcon, 
    PlusCircledIcon, MinusIcon, MinusCircledIcon, CaretDownIcon, CaretSortIcon, CaretLeftIcon, 
    CaretRightIcon, TrashIcon, CubeIcon, HeartIcon, BackpackIcon, CircleBackslashIcon, InfoCircledIcon, 
    EnvelopeOpenIcon, EnvelopeClosedIcon, PaperPlaneIcon, LockClosedIcon, LockOpen2Icon, 
    SliderIcon, SymbolIcon, FontSizeIcon, CursorArrowIcon, CursorTextIcon, TwitterLogoIcon, ResetIcon, 
    ClockIcon, IdCardIcon, CounterClockwiseClockIcon, HamburgerMenuIcon, DotsHorizontalIcon, DotsVerticalIcon, 
    Share1Icon, DownloadIcon, UploadIcon, ImageIcon, ExternalLinkIcon, Link2Icon, ScissorsIcon, KeyboardIcon,
    EyeOpenIcon, AvatarIcon, DashboardIcon, ListBulletIcon, ActivityLogIcon, BarChartIcon, PieChartIcon,
    DropdownMenuIcon, QuoteIcon, GlobeIcon, RocketIcon, BookmarkIcon, BookmarkFilledIcon, DrawingPinIcon,
    DrawingPinFilledIcon, ReaderIcon, ZoomInIcon, ZoomOutIcon, DoubleArrowLeftIcon, DoubleArrowRightIcon,
    DoubleArrowUpIcon, DoubleArrowDownIcon, TokensIcon, MixerHorizontalIcon, MixerVerticalIcon, ArchiveIcon,
    CrumpledPaperIcon, StarFilledIcon, StopwatchIcon, LapTimerIcon, ClipboardIcon, ClipboardCopyIcon,
    DesktopIcon, LaptopIcon, MobileIcon, EnterFullScreenIcon, ExitFullScreenIcon, ChatBubbleIcon} from '@radix-ui/react-icons';

const iconMap: Record<string, React.ComponentType<any>> = {
  sun: SunIcon,
  moon: MoonIcon,
  settings: GearIcon,
  user: PersonIcon,
  cube: CubeIcon,
  heart: HeartIcon,
  backpack: BackpackIcon,
  questionmark: QuestionMarkIcon,
  questionmarkcircled: QuestionMarkCircledIcon,
  checkcircled: CheckCircledIcon,
  check: CheckIcon,
  chat: ChatBubbleIcon,
  exit: ExitIcon,
  calendar: CalendarIcon,
  camera: CameraIcon,
  star: StarIcon,
  starfilled: StarFilledIcon,
  code: CodeIcon,
  plus: PlusIcon,
  pluscircled: PlusCircledIcon,
  minus: MinusIcon,
  minuscircled: MinusCircledIcon,
  codesandbox: CodeSandboxLogoIcon,
  cardstack: CardStackIcon,
  cardstackminus: CardStackMinusIcon,
  cardstackplus: CardStackPlusIcon,
  stack: StackIcon,
  layers: LayersIcon,
  input: InputIcon,
  search: MagnifyingGlassIcon,
  cancel: Cross1Icon,
  close: Cross2Icon,
  crosshair: Crosshair2Icon,
  github: GitHubLogoIcon,
  instagram: InstagramLogoIcon,
  twitter: TwitterLogoIcon,
  linkedin: LinkedInLogoIcon,
  file: FileIcon,
  home: HomeIcon,
  delete: TrashIcon,
  bell: BellIcon,
  switch: SwitchIcon,
  caretup: CaretUpIcon,
  caretdown: CaretDownIcon,
  caretleft: CaretLeftIcon,
  caretright: CaretRightIcon,
  caretsort: CaretSortIcon,
  doublearrowup: DoubleArrowUpIcon,
  doublearrowdown: DoubleArrowDownIcon,
  doublearrowleft: DoubleArrowLeftIcon,
  doublearrowright: DoubleArrowRightIcon,
  notallowed: CircleBackslashIcon,
  infocircled: InfoCircledIcon,
  envelopeopen: EnvelopeOpenIcon,
  envelopeclosed: EnvelopeClosedIcon,
  paperplane: PaperPlaneIcon,
  lockclosed: LockClosedIcon,
  lockopen: LockOpen2Icon,
  slider: SliderIcon,
  refresh: SymbolIcon,
  fontsize: FontSizeIcon,
  cursorarrow: CursorArrowIcon,
  cursortext: CursorTextIcon,
  reset: ResetIcon,
  clock: ClockIcon,
  idcard: IdCardIcon,
  history: CounterClockwiseClockIcon,
  hamburgermenu: HamburgerMenuIcon,
  elipsishorizontal: DotsHorizontalIcon,
  elipsisvertical: DotsVerticalIcon,
  share: Share1Icon,
  download: DownloadIcon,
  upload: UploadIcon,
  image: ImageIcon,
  externallink: ExternalLinkIcon,
  hyperlink: Link2Icon,
  scissors: ScissorsIcon,
  keyboard: KeyboardIcon,
  eye: EyeOpenIcon,
  avatar: AvatarIcon,
  dashboard: DashboardIcon,
  listbullet: ListBulletIcon,
  activitylog: ActivityLogIcon,
  barchart: BarChartIcon,
  piechart: PieChartIcon,
  dropdown: DropdownMenuIcon,
  quote: QuoteIcon,
  globe: GlobeIcon,
  rocket: RocketIcon,
  bookmark: BookmarkIcon,
  bookmarkfilled: BookmarkFilledIcon,
  pin: DrawingPinIcon,
  pinfilled: DrawingPinFilledIcon,
  reader: ReaderIcon,
  tokens: TokensIcon,
  zoomin: ZoomInIcon,
  zoomout: ZoomOutIcon,
  mixerhorizontal: MixerHorizontalIcon,
  mixervertical: MixerVerticalIcon,
  archive: ArchiveIcon,
  crumpledpaper: CrumpledPaperIcon,
  stopwatch: StopwatchIcon,
  laptimer: LapTimerIcon,
  clipboard: ClipboardIcon,
  clipboardcopy: ClipboardCopyIcon,
  desktop: DesktopIcon,
  laptop: LaptopIcon,
  mobile: MobileIcon,
  enterfullscreen: EnterFullScreenIcon,
  exitfullscreen: ExitFullScreenIcon
};

export const Icon = ({ name, ...props }: { name: string }) => {
  const IconComponent = iconMap[name];

  if (!IconComponent) return null;

  return <IconComponent {...props} />;
};